
<div class="headerright">
	<div class="dropdown userinfo">
		<a class="dropdown-toggle" data-toggle="dropdown" data-target="#"
			href="/home">Hi, Edwin! <b class="caret"></b></a>
		<ul class="dropdown-menu">
			<li><a href="/home"><span class="icon-edit"></span> Edit Profile</a></li>
			<li><a href=""><span class="icon-wrench"></span> Account Settings</a></li>
			<li class="divider"></li>
			<li><a href="/logout"><span class="icon-off"></span> Sign Out</a></li>
		</ul>
	</div>
	<!--dropdown-->
</div>
<!--headerright-->