<?php
$url = $this->getHelperPluginManager()
    ->getServiceLocator()
    ->get('request')
    ->getUri()
    ->getPath();
$uriParts = explode("/", $url);
$url = $uriParts[1];
?>
<div class="leftmenu">
	<ul class="nav nav-tabs nav-stacked">
		<li class="nav-header">Main Navigation</li>
		<li <?php echo $url=="home"?"class='active'":""; ?>><a href="/home"><span
				class="icon-home"></span> Dashboard</a></li>
		<li class="<?php echo $url=="manage"?"active":""; ?> dropdown"><a
			href="javascript:void(0);"><span class="icon-wrench"></span>Manage</a>
			<ul <?php echo $url=="manage"?"style='display:block;'":""; ?>>
				<li><a href="/manage/states">States</a></li>
				<li><a href="/manage/cities">Cities</a></li>
				<li><a href="javascript:void(0);">Areas</a></li>
				<li><a href="javascript:void(0);">Restaurants</a></li>
			</ul></li>
	</ul>
</div>
<!--leftmenu-->