
<div class="leftmenu">
	<ul class="nav nav-tabs nav-stacked">
		<li class="nav-header">Main Navigation</li>
		<li class="active"><a href="/home"><span class="icon-home"></span>
				Dashboard</a></li>
		<li class="dropdown"><a href="javascript:void(0);"><span
				class="icon-wrench"></span>Manage</a>
			<ul>
				<li><a href="/manage/states">States</a></li>
				<li><a href="javascript:void(0);">Cities</a></li>
				<li><a href="javascript:void(0);">Areas</a></li>
				<li><a href="javascript:void(0);">Restaurants</a></li>
			</ul></li>
	</ul>
</div>
<!--leftmenu-->