<?php
if (isset($this->errorMessages)) {
    ?>
<div class="alert alert-error alert-danger">
	<button aria-hidden="true" data-dismiss="alert" class="close"
		type="button">×</button>
	<?php 
	   foreach($this->errorMessages as $message){
            echo "<li>".$message."</li>";
       }
	?>
</div>
<?php
} else {
    $flash = $this->flashMessenger();
    if (isset($flash)) {
        $flash->setMessageOpenFormat('<div%s>
                             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                         </button>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
        
        echo $flash->render('error', array(
            'alert',
            'alert-error',
            'alert-danger'
        ));
        echo $flash->render('info', array(
            'alert',
            'alert-dismissable',
            'alert-info'
        ));
        echo $flash->render('default', array(
            'alert',
            'alert-dismissable',
            'alert-warning'
        ));
        echo $flash->render('success', array(
            'alert',
            'alert-dismissable',
            'alert-success'
        ));
    }
}
?>