<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle("Administrator | GrubFiesta")->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.default.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css');
        
        ?>
        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-migrate.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>
    </head>
<body>
	<div class="mainwrapper">
		<div class="rightpanel" >
			<div class="contentinner wrapper404"style="margin-top: 50px;">
			<h1>Not Found.</h1>
				<p>The page you are looking for is not found. This could be for
					several reasons...</p>
				<ul>
					<li><span class="icon-check"></span> It never existed.</li>
					<li><span class="icon-check"></span> It got deleted for some
						reason.</li>
					<li><span class="icon-check"></span> You were looking for something
						that is not here.</li>
					<li><span class="icon-check"></span> You like this page.</li>
				</ul>
				<br>
				<button onclick="history.back()" class="btn btn-primary">Go Back to
					Previous Page</button>
				&nbsp;
				<a class="btn" href="/home">Go Back to Dashboard</a>
			</div>
		</div>
	</div>
</body>
</html>