<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle("Administrator | GrubFiesta")->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.default.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css');
        
        ?>
        <!-- Scripts -->
        <?php
        
echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-migrate.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>
    </head>
<body class="loginbody">

	<div class="loginwrapper">
<?php

$flash = $this->flashMessenger();
if (isset($flash)) {
    $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');
    
    echo $flash->render('error', array(
        'alert',
        'alert-error',
        'alert-danger'
    ));
    echo $flash->render('info', array(
        'alert',
        'alert-dismissable',
        'alert-info'
    ));
    echo $flash->render('default', array(
        'alert',
        'alert-dismissable',
        'alert-warning'
    ));
    echo $flash->render('success', array(
        'alert',
        'alert-dismissable',
        'alert-success'
    ));
}
?>
<?php echo $this->content; ?>
</div>
	<!--loginwrapper-->
</body>
</html>
