<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle("Administrator | GrubFiesta")->setSeparator(' - ')->setAutoEscape(false)?>
        <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.default.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css');
        
        ?>
        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/custom.js')
            ->prependFile($this->basePath() . '/js/bootbox.min.js')
            ->prependFile($this->basePath().'/js/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/jquery.cookie.js')
            ->prependFile($this->basePath() . '/js/jquery.flot.resize.min.js')
            ->prependFile($this->basePath() . '/js/jquery.flot.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui-1.9.2.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-migrate.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js');
        ?>
    </head>
<body>

	<div class="mainwrapper">

		<!-- START OF LEFT PANEL -->
		<div class="leftpanel">

			<div class="logopanel">
				<h1>
					<a href="/home">GrubFiesta</a>
				</h1>
			</div>
			<!--logopanel-->

			<div class="datewidget">Today is <?php echo date("l, M d, Y h:i:a"); ?></div>
            <?php echo $this->partial('layout/leftmenu'); ?>
            <!-- leftmenu -->
		</div>
		<!--mainleft-->
		<!-- END OF LEFT PANEL -->
		<!-- START OF RIGHT PANEL -->
		<div class="rightpanel">
			<div class="headerpanel">
				<a href="" class="showmenu"></a>
                 <?php echo $this->partial('layout/header'); ?>
				<!--headerright-->
			</div>
			<!--headerpanel-->
			<div class="breadcrumbwidget">
				<ul class="breadcrumb">
					<li><a href="/home">Home</a> <span class="divider">/</span></li>
					<li class="active">Dashboard</li>
				</ul>
			</div>
			<!--breadcrumbwidget-->
			<div class="pagetitle">
				<h1><?php echo isset($this->pageTitle)?$this->pageTitle:"--"; ?></h1>
				<span><?php echo isset($this->pageDescr)?$this->pageDescr:"--"; ?></span>
			</div>
			<!--pagetitle-->

			<div class="maincontent">
				<div class="contentinner content-dashboard">
                    <?php echo $this->partial('layout/message') ?>
                    <!-- alert -->
					<div class="row-fluid">
				        <?php echo $this->content; ?>
				    </div>    
				</div>
				<!--contentinner-->
			</div>
			<!--maincontent-->
		</div>
		<!--mainright-->
		<!-- END OF RIGHT PANEL -->
		<div class="clearfix"></div>
		<?php echo $this->partial('layout/footer'); ?>
		<!--footer-->
	</div>
	<!--mainwrapper-->
</body>
</html>