<div class="span">
	<h4 class="widgettitle nomargin shadowed">States</h4>
	<div class="widgetcontent bordered shadowed">
		  <?php
    $form = $this->stateForm;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array(
        'controller' => 'States',
        'action' => 'add'
    )));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
            <?php
            echo $this->formElement($form->get('id'));
            echo $this->formElement($form->get('latitude'));
            echo $this->formElement($form->get('longitude'));
            ?>
            <?php
            echo $this->formElement($form->get('state'));
            echo $this->formElementErrors($form->get('state'));
            ?>
            <p>
				<?php echo $this->formElement($form->get('submit')); ?>
			</p>
		<hr />
		<table class="table table-bordered" id="dyntable">
			<thead>
				<tr>
					<th class="head0" width="40%">State</th>
					<th class="head1" width="50%">Action</th>
				</tr>
			</thead>
			<tbody>
			<?php
if (isset($this->states) && ! empty($this->states)) {
    foreach ($this->states as $state) {
        ?>
				<tr>
					<td><?php echo $state['state']; ?></td>
					<td><a href="javascript:void(0);"
						id="edit-<?php echo $state['id']; ?>"
						class="btn btn-info edit-state"><i class="iconfa-pencil"></i></a>
						<a href="/state/delete/<?php echo $state['id']; ?>"
						class="btn btn-danger delete-item"><i
							class="icon-trash icon-white"></i></a></td>
				</tr>
			<?php }}else{ ?>
			     <tr>
					<td colspan="2">No states found</td>
				</tr>
			<?php } ?>	
			</tbody>
		</table>

	</div>
	<!--widgetcontent-->
</div>
<script>
jQuery(document).ready(function(){
	if(jQuery('#dyntable').length > 0) {
		jQuery('#dyntable').dataTable({
			"sPaginationType": "full_numbers",
			"bFilter": false,
			"aaSortingFixed": [[0,'asc']],
			"fnDrawCallback": function(oSettings) {
				//jQuery.uniform.update();
			}
		});
	}
	jQuery("#state-form").validate();
});
</script>