<?php
// Generated by ZF2's ./bin/classmap_generator.php
/*return array(
    'Admin\Module'                        => __DIR__ . '/Module.php',
    'Admin\Controller\SkeletonController' => __DIR__ . '/src/Admin/Controller/IndexController.php'
);*/
return array();