<!DOCTYPE html>
<html lang="en">
    <head>
		<meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
        <title>LabourValley | Coming Soon</title>
		<meta name="robots" content="noodp,noydir"/>
		<meta name="description" content="LabourValley is a portal where you can find any type of labour, we provide on-site labour serives."/>
		<meta name="keywords" content="labour,labours,employment,work,chotakaam,plumbers, electrician, hard labour "/>
		<link rel="canonical" href="http://labourvalley.com/" />
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="website" />
		<meta property="og:title" content="LabourValley" />
		<meta property="og:description" content="Labours : You name it we will arrange it." />
		<meta property="og:url" content="http://labourvalley.com/" />
		<meta property="og:site_name" content="LabourValley" />
		<meta property="og:image" content="http://labourvalley.com/public/images/labour3.png" />

        <meta name="author" content="Krunal Goswami" />
        <link rel="shortcut icon" href="favicon.ico"> 
        <link href='http://fonts.googleapis.com/css?family=Chivo' rel='stylesheet' type='text/css' />
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/cssm/style.css')
                        ->prependStylesheet($this->basePath() . '/cssm/font/stylesheet.css') ?>
    </head>
    <body>
        <div class="container">
        	<div class="inner">
        	<div class="left-block">
            	<img src="<?php echo $this->basePath(); ?>images/cs.png" />
                <p> We will be here with some cool creative stuff</p>
            </div>
            <div class="right-block">
            	<img src="<?php echo $this->basePath(); ?>images/labour2.png" />
            </div>
            </div>
        <div class="clr">&nbsp;</div>
          	<div class="bottom">
            	<div class="inner">
                <p>Powered by : <a href="http://codebyte.in">CodeByte</a></p>
            </div>
            </div>
        </div>
    </body>
</html>
