<div class="loginwrap zindex100 animate2 bounceInDown">
	<h1 class="logintitle">
		<span class="iconfa-lock"></span> Sign In <span class="subtitle">Hello! Sign in to get you started!</span>
	</h1>
	<div class="loginwrapperinner">
		  <?php 
                $form = $this->loginForm;
                $form->prepare();
                $form->setAttribute('action', $this->url(NULL,array('controller'=>'Login', 'action' => 'index')));
                $form->setAttribute('method', 'post');
                echo $this->form()->openTag($form);
            ?>
			<p class="animate4 bounceIn">
				<?php
                    echo $this->formElement($form->get('username'));
                    echo $this->formElementErrors($form->get('username'));
                ?>
			</p>
			<p class="animate5 bounceIn">
				<?php
                    echo $this->formElement($form->get('password'));
                    echo $this->formElementErrors($form->get('password'));
                ?>
			</p>
			<p class="animate6 bounceIn">
				<?php echo $this->formElement($form->get('submit')); ?>
			</p>
			<p class="animate7 fadeIn">
				<a href=""><span class="icon-question-sign icon-white"></span>
					Forgot Password?</a>
			</p>
	</div>
	<!--loginwrapperinner-->
</div>
<div class="loginshadow animate3 fadeInUp"></div>

<script type="text/javascript">
jQuery.noConflict();

jQuery(document).ready(function(){
	
	var anievent = (jQuery.browser.webkit)? 'webkitAnimationEnd' : 'animationend';
	jQuery('.loginwrap').bind(anievent,function(){
		jQuery(this).removeClass('animate2 bounceInDown');
	});
	
	jQuery('#username,#password').focus(function(){
		if(jQuery(this).hasClass('error')) jQuery(this).removeClass('error');
	});
	
	jQuery('#loginform button').click(function(){
		if(!jQuery.browser.msie) {
			if(jQuery('#username').val() == '' || jQuery('#password').val() == '') {
				if(jQuery('#username').val() == '') jQuery('#username').addClass('error'); else jQuery('#username').removeClass('error');
				if(jQuery('#password').val() == '') jQuery('#password').addClass('error'); else jQuery('#password').removeClass('error');
				jQuery('.loginwrap').addClass('animate0 wobble').bind(anievent,function(){
					jQuery(this).removeClass('animate0 wobble');
				});
			} else {
				jQuery('.loginwrapper').addClass('animate0 fadeOutUp').bind(anievent,function(){
					jQuery('#loginform').submit();
				});
			}
			return false;
		}
	});
});
</script>